CollegeManagementSystem/Areas/Admin/Controllers/MainController.cs
using CollegeManagementSystem.Models.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CollegeManagementSystem.Areas.Admin.Controllers
{
    
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MainController : Controller
    {
        private readonly AppDbContext context;

        public MainController(AppDbContext _context)
        {
            this.context = _context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ManageStudents()
        {
            return RedirectToAction(nameof(StudentController.GetAll),"Student");
        }

        public IActionResult ManageSections()
        {
            return RedirectToAction(nameof(SectionController.GetAllSections),"Section");
        }   

        public IActionResult ManageCourses()
        {
            return RedirectToAction(nameof(CourseController.GetAllCourses),"Course");
        }
    }
}

CollegeManagementSystem/Areas/Admin/Views/Main/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Index";
}

<head>
    <title>Admin Dashboard</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-3">
                <h2>Admin Dashboard </h2>
                <ul class="list-group">
                    <li class="list-group-item">
                        @Html.ActionLink("Manage Students", "ManageStudents", "Main")
                    </li>
                    <li class="list-group-item">
                        @Html.ActionLink("Manage Sections", "ManageSections", "Main")
                    </li>
                    <li class="list-group-item">
                        @Html.ActionLink("Manage Courses", "ManageCourses", "Main")
                    </li>
                </ul>
            </div>
        </div>
    </div>
</body>

CollegeManagementSystem/Areas/Admin/Views/Main/ManageCourses.cshtml
@model IEnumerable<CollegeManagementSystem.Models.Entities.Course>

@{
    Layout = "_Layout";
    ViewData["Title"] = "ManageCourses";
}

<h1>ManageCourses</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credits)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CourseId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CourseId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CourseId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CollegeManagementSystem/Areas/Admin/Views/Main/ManageSections.cshtml
@model IEnumerable<CollegeManagementSystem.Models.Entities.Section>

@{
    Layout = "_Layout";
    ViewData["Title"] = "ManageSections";
}

<h1>Manage Sections</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Add New Section</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instructor.InstructorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SectionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SectionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SectionId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>